#!/usr/bin/env bash

#   Copyright The containerd Authors.

#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at

#       http://www.apache.org/licenses/LICENSE-2.0

#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

#
# Install proto generation tools for local development.
#
# The buf version is read from script/buf-version, which is the single source
# of truth shared with the CI workflow.
#
set -eu -o pipefail

cd "$(dirname "$0")/.."

BUF_VERSION=$(cat script/buf-version)

go install "github.com/bufbuild/buf/cmd/buf@v${BUF_VERSION}"
go install github.com/containerd/protobuild/cmd/go-fix-acronym@v0.3.0
